// pages/tictactoe.tsx
import type { NextPage } from "next";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import Link from "next/link";
import styles from "../styles/TicTacToe.module.css";

const Home: NextPage = () => {
    return (
        <div className="bg-white border min-h-screen">
            <div className="container flex justify-between px-6 py-6 container mx-auto">
                <Link href="/">
                    <a className="text-xl font-bold text-gray-800 md:text-2xl hover:text-red">
                        0xcacti
                    </a>
                </Link>
                <ConnectButton />
            </div>
            <div className="flex flex-row h-screen border border-red mx-auto justify-center">
                <div
                    className="flex flex-col border border-blue h-2/3 w-1/3"
                    style={{ height: "600px", width: "600px" }}
                >
                    <div>
                        <div className={styles.boardContainer}>
                            <div className={styles.crossVerticalLeft}></div>
                            <div className={styles.crossVerticalRight}></div>
                            <div className={styles.crossHorizontalTop}></div>
                            <div className={styles.crossHorizontalBottom}></div>

                            <div className={styles.o00}></div>
                            <div className={styles.o01}></div>
                            <div className={styles.o21}></div>
                            <div className={styles.o22}></div>
                            <div className={styles.x02Left}></div>
                            <div className={styles.x02Right}></div>
                            <div className={styles.x10Left}></div>
                            <div className={styles.x10Right}></div>
                            <div className={styles.x11Left}></div>
                            <div className={styles.x11Right}></div>
                            <div className={styles.x12Left}></div>
                            <div className={styles.x12Right}></div>
                            <div className={styles.x20Left}></div>
                            <div className={styles.x20Right}></div>
                        </div>
                    </div>
                </div>
                <div className="border border-black text-center p-5">
                    <div className="border bg-blue p-2">
                        <h1>New Game</h1>
                    </div>
                    <div className="border bg-red p-2">
                        <h1>Find / Mint Existing Game</h1>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Home;

// src/routes/tictactoe/rendering/TicTacToe.svelte
<script>
  import "./tictactoe.css";
  import Tabs from "./Tabs.svelte";

  const tabs = [
    {
      id: 1,
      title: "Tab 1",
      content: "This is the content of Tab 1.",
    },
    {
      id: 2,
      title: "Tab 2",
      content: "This is the content of Tab 2.",
    },
    {
      id: 3,
      title: "Tab 3",
      content: "This is the content of Tab 3.",
    },
  ];
</script>

<div class="gameboard-container">
  <div class="container mx-auto mt-10">
    <Tabs {tabs} />
  </div>
  <!-- <div class="flex align-center border">
    <div class="board-container border">
      <div class="crossVerticalLeft" />
      <div class="crossVerticalRight" />
      <div class="crossHorizontalTop" />
      <div class="crossHorizontalBottom" />
      <div class="o00" />
      <div class="o01" />
      <div class="o02" />
      <div class="o10" />
      <div class="o11" />
      <div class="o12" />
      <div class="o20" />
      <div class="o21" />
      <div class="o22" />
      <div class="x00Left" />
      <div class="x00Right" />
      <div class="x01Left" />
      <div class="x01Right" />
      <div class="x02Left" />
      <div class="x02Right" />
      <div class="x10Left" />
      <div class="x10Right" />
      <div class="x11Left" />
      <div class="x11Right" />
      <div class="x12Left" />
      <div class="x12Right" />
      <div class="x20Left" />
      <div class="x20Right" />
      <div class="x21Left" />
      <div class="x21Right" />
      <div class="x22Left" />
      <div class="x22Right" />
    </div>
  </div> -->
</div>
