// src/routes/Ascii.svelte
<div class="ascii-container">
  <pre class="text-teal-500"> 
          
        |\ _ /|   
       ( o  o )
        &gt . &lt/
        |    \
        |  |  \
        |  |   | 
       (_(_f_, ) 0xcacti
             //
            ((
             ))  
            ((
             v 
  
    </pre>
</div>

// components/Ascii.tsx
import "../styles/Ascii.module.css";
const Ascii = () => {
    return (
        
            <pre className="preWrapper">
            {`
    |\\_ /|   
( o  o )
> . </
|    \\
 |  |  \\
   |  |   | 
         (_(_f_, ) 0xcacti
      //
    ((
       ))  
    ((
     v 
            `}
            </pre>

    );
};

export default Ascii;
